name: wind-power-forecast
channels:
  - defaults
dependencies:
  - python=3.9
  - pip>20
  - numpy>1.19
  - scikit-learn>0.23
  - pip:
    - mlflow
    - matplotlib>3
    - tqdm
    - termcolor
    - azureml
    - azureml-core
